version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: ./dev-docker/Dockerfile
    ports:
      - $HTTP_EXPOSING_PORT:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./dev-docker/config/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./dev-docker/config/php/custom.ini:/etc/php7/conf.d/custom.ini
      - ./dev-docker/config/php/fpm/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./dev-docker/config/others/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./dev-docker/log/nginx/:/var/log/nginx/
      - ./:/var/www/html
    env_file:
      - ./.env
    environment:
      - APP_URL=http://127.0.0.1:${HTTP_EXPOSING_PORT}
      - DB_HOST=mysql8
      - DB_PORT=3306

  mysql8:
    image: mysql:8
    command: mysqld --authentication_policy=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 29036:3306
    volumes:
      - mysql_db:/var/lib/mysql
      - './dev-docker/mysql8/my.cnf:/etc/mysql/conf.d/my.cnf'
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
volumes:
  mysql_db:
